=head1 AUTHOR

This is part of this EPrints 3.4 system. EPrints 3.4 is developed by EPrints Services

=head1 VERSION

EPrints Version: __VERSION__

=head1 CONTACT

For more information goto B<http://www.eprints.org/eprints-3.4/> which give information on mailing lists and the like.

EPrints Services may be contacted at B<support@eprints.org>

Should you need a real world address for some reason, EPrints Services can be contacted in the real world at

 EPrints Services
 Electronics and Computer Science
 University of Southampton
 SO17 1BJ
 United Kingdom

=head1 COPYRIGHT

__LICENSE__

