#!/usr/bin/perl

use EPrints;
use URI::Escape;

use strict;

my $repo = EPrints->new->current_repository;

my $plugin = $repo->plugin( "Export::".$repo->param( "format" ) );
$repo->not_found, exit if !defined $plugin;

my $dataset = $repo->dataset( $repo->param( "dataset" ) || "archive" );
$repo->not_found, exit if !defined $dataset;

my $dataobj = $dataset->dataobj( $repo->param( "dataobj" ) || $repo->param( $dataset->key_field->name ) );
$repo->not_found, exit if !defined $dataobj;

$repo->redirect( $plugin->dataobj_export_url( $dataobj ) );

=head1 COPYRIGHT

=for COPYRIGHT BEGIN

Copyright 2019 University of Southampton.
EPrints 3.4 is supplied by EPrints Services.

http://www.eprints.org/eprints-3.4/

=for COPYRIGHT END

=for LICENSE BEGIN

This file is part of EPrints 3.4 L<http://www.eprints.org/>.

EPrints 3.4 and this file are released under the terms of the
GNU Lesser General Public License version 3 as published by
the Free Software Foundation unless otherwise stated.

EPrints 3.4 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with EPrints 3.4.
If not, see L<http://www.gnu.org/licenses/>.

=for LICENSE END

