#!/usr/bin/perl -w

use EPrints;

use strict;

my $session = new EPrints::Session();
exit( 1 ) unless( defined $session );

my $url = "http://www.google.com/search?q=".$session->param( "q" );
$url .= "+site:".$session->config( "host" ) if defined $session->config( "host" );
$url .= "+site:".$session->config( "securehost" ) unless defined $session->config( "host" );

$session->redirect( $url );

$session->terminate();
