#!/usr/bin/perl

######################################################################
#
#  EPrints User Login
#
######################################################################
#
#  __COPYRIGHT__
#
# Copyright 2023 University of Southampton.
# EPrints 3.4 is supplied by EPrints Services.
#
# http://www.eprints.org/eprints-3.4/
#
#  __LICENSE__
#
# This file is part of EPrints 3.4 L<http://www.eprints.org/>.
#
# EPrints 3.4 and this file are released under the terms of the
# GNU Lesser General Public License version 3 as published by
# the Free Software Foundation unless otherwise stated.
#
# EPrints 3.4 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with EPrints 3.4.
# If not, see L<http://www.gnu.org/licenses/>.
#
######################################################################


use EPrints;

use strict;

my $repo = EPrints->new->current_repository;

my $url = $repo->param( "target" );

#unset $url if it doesn't have the same hostname as the repository
if ( defined $url )
{	
        my $target_uri = URI->new( $url );
        my $repository_uri = URI->new( $repo->config( 'base_url' ) );
        if ( !$target_uri->can( 'host' ) || $target_uri->host ne $repository_uri->host )
        {
                $url = undef;
        }
}

$url = $repo->config( "rel_cgipath" ) . "/users/home" if !defined $url;

$repo->redirect( $url );
