#!/usr/bin/perl

use FindBin;
use lib "$FindBin::Bin/../perl_lib";

use ParaTools::DocParser::Standard;
use Pod::Usage;
use Getopt::Long;
use Encode;

=head1 NAME

txt2refs - extract bibliography from plain text

=head1 SYNOPSIS

doc2txt <input.txt | -> <output.txt | ->

=head1 OPTIONS

=over 4

=item --enc=UTF-8

Set the output encoding (any supported by Encode). Defaults to UTF-8.

=cut

use strict;
use warnings;

my(
	$opt_enc,
	$opt_help,
);

GetOptions(
	'enc=s' => \$opt_enc,
	'help' => \$opt_help,
) or pod2usage();

pod2usage(1) if $opt_help;
pod2usage() if @ARGV != 2;

my( $ifh, $ofh );
if( $ARGV[0] eq "-" )
{
	$ifh = \*STDIN;
}
else
{
	open($ifh, "<", $ARGV[0]) or die "Error open $ARGV[0]: $!";
}
if( $ARGV[1] eq '-' )
{
	$ofh = \*STDOUT;
}
else
{
	open($ofh, ">", $ARGV[1]) or die "Error opening $ARGV[1]: $!";
}

binmode($ifh, ":utf8");
if( $opt_enc )
{
	if( !binmode($ofh, ":encoding($opt_enc)") )
	{
		die join(', ', Encode->encodings(":all"))."\n";
	}
}
else
{
	binmode($ofh, ":utf8");
}

#local $ParaTools::DocParser::Standard::DEBUG = 1;
my $parser = ParaTools::DocParser::Standard->new;
my $buffer;
{
local $/;
$buffer = <$ifh>;
}

my @refs = $parser->parse( $buffer );

print $ofh join("\n\n", @refs);

=head1 COPYRIGHT

=for COPYRIGHT BEGIN

Copyright 2019 University of Southampton.
EPrints 3.4 is supplied by EPrints Services.

http://www.eprints.org/eprints-3.4/

=for COPYRIGHT END

=for LICENSE BEGIN

This file is part of EPrints 3.4 L<http://www.eprints.org/>.

EPrints 3.4 and this file are released under the terms of the
GNU Lesser General Public License version 3 as published by
the Free Software Foundation unless otherwise stated.

EPrints 3.4 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with EPrints 3.4.
If not, see L<http://www.gnu.org/licenses/>.

=for LICENSE END

