#!/usr/bin/perl -w
use FindBin;
use lib "$FindBin::Bin/../perl_lib";
use EPrints;

######################################################################
#
#  __LICENSE__
#
######################################################################

=pod

=head1 NAME

B<update_phrase_file> - Not DOCd

=head1 SYNOPSIS

B<update_phrase_file> I<archive_cfg_directory> I<old_english_phrase_file> I<new_english_phrase_file> I<old_translated_phrase_file>

=head1 DESCRIPTION

=back   


=cut

use strict;
use Getopt::Long;
use Pod::Usage;

my $version = 0;
my $verbose = 0;
my $quiet = 0;
my $help = 0;
my $man = 0;

GetOptions( 
	'help|?' => \$help,
	'man' => \$man,
	'version' => \$version,
	'verbose+' => \$verbose,
	'silent' => \$quiet,
	'quiet' => \$quiet
) || pod2usage( 2 );
EPrints::Utils::cmd_version( "update_phrase_file" ) if $version;
pod2usage( 1 ) if $help;
pod2usage( -exitstatus => 0, -verbose => 2 ) if $man;
pod2usage( 2 ) if( scalar @ARGV != 4 ); 

my $noise = 1;
$noise = 0 if( $quiet );
$noise = 1+$verbose if( $verbose );

# Set STDOUT to auto flush (without needing a \n)
$|=1;

my $basepath = $ARGV[0] !~ /\/$/ ? $ARGV[0] . '/' : $ARGV[0];
my $old_phr_en_filename = $ARGV[1] !~ /^\// ? $basepath . $ARGV[1] : $ARGV[1];
my $new_phr_en_filename = $ARGV[2] !~ /^\// ? $basepath . $ARGV[2] : $ARGV[2];
my $old_phr_other_filename = $ARGV[3] !~ /^\// ? $basepath . $ARGV[3] : $ARGV[3];
my $old_phr_en = EPrints::XML::parse_xml( $old_phr_en_filename, $basepath, 1);
my $new_phr_en = EPrints::XML::parse_xml( $new_phr_en_filename, $basepath, 1);
my $old_phr_other = EPrints::XML::parse_xml( $old_phr_other_filename, $basepath, 1);

my $phrases;

my $old_phr_en_phrases = {};
$phrases = ( $old_phr_en->getElementsByTagName( "phrases" ) )[0];
foreach my $node ( $phrases->getChildNodes )
{
	next unless( EPrints::XML::is_dom( $node, "Element" ) );
	my $ref = $node->getAttribute( "ref" );
	$old_phr_en_phrases->{$ref} = $node if defined $ref && defined $old_phr_en_phrases->{$ref};
}

my $old_phr_other_phrases = {};
$phrases = ( $old_phr_other->getElementsByTagName( "phrases" ) )[0];
foreach my $node ( $phrases->getChildNodes )
{
	next unless( EPrints::XML::is_dom( $node, "Element" ) );
	my $ref = $node->getAttribute( "ref" );
	$old_phr_other_phrases->{$ref} = $node if defined $ref && defined $old_phr_other_phrases->{$ref};
}

$phrases = ( $new_phr_en->getElementsByTagName( "phrases" ) )[0];
foreach my $node ( $phrases->getChildNodes )
{
	next unless( EPrints::XML::is_dom( $node, "Element" ) );
	my $ref= $node->getAttribute( "ref" );
	print $ref."   ";
	if( !defined $old_phr_en_phrases->{$ref} )
	{
		my $c1 = $new_phr_en->createComment( " TRANSLATE $ref (New) " );
		$phrases->insertBefore( $c1, $node );
		$phrases->insertBefore( $new_phr_en->createTextNode( "\n" ), $node );
		print "NEW";
	}
	elsif( $node->toString eq $old_phr_en_phrases->{$ref}->toString )
	{
		my $forign = EPrints::XML::clone_and_own( $old_phr_other_phrases->{$ref}, $new_phr_en, 1 );
		print "same";
		$phrases->replaceChild( $forign, $node );
	}
	else
	{
		my @c = ();
		push @c, "\nTRANSLATE $ref (Changed)\nOLD ENGLISH: ";
		foreach( $old_phr_en_phrases->{$ref}->getChildNodes )
		{
			push @c, $_->toString;
		}
		push @c, "\nOLD TRANSLATION: ";
		foreach( $old_phr_other_phrases->{$ref}->getChildNodes )
		{
			push @c, $_->toString;
		}
		push @c, "\n";

		my $c1 = $new_phr_en->createComment( join( "", @c ) );
		$phrases->insertBefore( $c1, $node );
		$phrases->insertBefore( $new_phr_en->createTextNode( "\n" ), $node );
		print "DIFF";
	}
	print "\n";
}

print $new_phr_en->toString;

exit;

=head1 COPYRIGHT

=for COPYRIGHT BEGIN

Copyright 2021 University of Southampton.
EPrints 3.4 is supplied by EPrints Services.

http://www.eprints.org/eprints-3.4/

=for COPYRIGHT END

=for LICENSE BEGIN

This file is part of EPrints 3.4 L<http://www.eprints.org/>.

EPrints 3.4 and this file are released under the terms of the
GNU Lesser General Public License version 3 as published by
the Free Software Foundation unless otherwise stated.

EPrints 3.4 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with EPrints 3.4.
If not, see L<http://www.gnu.org/licenses/>.

=for LICENSE END

